import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WhitePlates",
  description: "Generated by WhitePlates",
};

export default function RootLayout({ children }) {
  return (
      <html lang='en'>      
      <body>        
        <Provider>{children}</Provider>     
      </body>    
      </html>
  );
}
